# Generated by Django 6.1.1 on 2026-10-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_turf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf',
            name='location',
        ),
        migrations.AddField(
            model_name='turf',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='turf',
            name='match_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turf',
            name='time',
            field=models.TimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='turf',
            name='fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='turf',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
