# Generated by Django 6.1.1 on 2026-10-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_turf', '0002_remove_turf_location_turf_duration_turf_match_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turf',
            old_name='name',
            new_name='team_name',
        ),
        migrations.RemoveField(
            model_name='turf',
            name='match_date',
        ),
        migrations.RemoveField(
            model_name='turf',
            name='time',
        ),
        migrations.AddField(
            model_name='turf',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='turf',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='turf',
            name='fee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='turf',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
