# Generated by Django 6.1.1 on 2026-09-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('Time', models.TimeField(editable=False, null=True)),
                ('date', models.DateField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
