# Generated by Django 6.1.1 on 2026-10-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='team_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='date',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='email',
        ),
        migrations.AddField(
            model_name='slot',
            name='fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='slot',
            name='match_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='slot',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
